spring:
  datasource:
    url: jdbc:mysql://192.168.197.112:3306/eims?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Pang_141413
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    druid:
      filters: wall,stat
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
      
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.css,*.ico,*.png,*.jpg,/druid/*'
  redis:
    host: 192.168.197.112
    port: 6379
  
  rabbitmq:
    host: 192.168.197.112
    password: guest
    username: guest
    
  mail:
    username: pangruting@qq.com
    password: bmicvwcznleaehag
    host: smtp.qq.com
  
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  
    
#elasticsearch7.10+配置
#elasticsearch:
#  address: 192.168.197.112:9200
#  schema: http
#  connectTimeout: 5000
#  socketTimeout: 5000
#  connectionRequestTimeout: 5000
#  maxConnectNum: 100
#  maxConnectPerRoute: 100


#mybatisplus配置  
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


#指标监控配置
management:
  
  endpoints:
    enabled-by-default: true
    
    web:
      exposure:
        include: '*' # 以web方式暴露所有端点
  endpoint:
    health:
      show-details: always   